import React, { useState } from 'react';
import { File, Folder, ExternalLink, Play, Terminal as TerminalIcon, Send } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

export type NativeBlock =
  | { type: 'artifact'; title: string; description?: string; url?: string; content?: string; action?: { label: string; action: string } }
  | { type: 'form'; title: string; fields: Array<{ name: string; label: string; type?: 'text' | 'email' | 'number' | 'textarea'; placeholder?: string; required?: boolean }>; submitLabel?: string; action?: string }
  | { type: 'table'; title?: string; columns: string[]; rows: Array<Array<string | number>> }
  | { type: 'chart'; title?: string; kind?: 'line' | 'bar'; xKey: string; data: Array<Record<string, string | number>>; series: string[] }
  | { type: 'file-tree'; title?: string; files: Array<{ path: string; type: 'file' | 'folder' }> }
  | { type: 'terminal'; title?: string; command?: string; output?: string; status?: 'running' | 'success' | 'error' };

export function NativeBlocks({ blocks, onAction }: { blocks: NativeBlock[]; onAction?: (action: string, payload?: Record<string, string>) => void }) {
  return <div className="mt-3 space-y-3">{blocks.map((block, index) => <NativeBlockView key={`${block.type}-${index}`} block={block} onAction={onAction} />)}</div>;
}

function NativeBlockView({ block, onAction }: { block: NativeBlock; onAction?: (action: string, payload?: Record<string, string>) => void }) {
  const shell = 'rounded-lg border border-[#292a32] bg-[#111216] overflow-hidden';
  if (block.type === 'artifact') return <div className={`${shell} p-4`}><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-medium text-zinc-200">{block.title}</div>{block.description && <div className="mt-1 text-xs text-zinc-500">{block.description}</div>}</div>{block.url && <a href={block.url} target="_blank" rel="noreferrer" className="text-zinc-400 hover:text-white"><ExternalLink className="h-4 w-4" /></a>}</div>{block.content && <pre className="mt-3 max-h-48 overflow-auto rounded-md bg-[#0b0c0f] p-3 text-xs text-zinc-400 whitespace-pre-wrap">{block.content}</pre>}{block.action && <button onClick={() => onAction?.(block.action!.action)} className="mt-3 rounded-md bg-zinc-100 px-3 py-1.5 text-xs font-medium text-zinc-950 hover:bg-white">{block.action.label}</button>}</div>;
  if (block.type === 'form') return <FormBlock block={block} onAction={onAction} shell={shell} />;
  if (block.type === 'table') return <div className={shell}><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-[#292a32] bg-[#15161b] text-zinc-400"><tr>{block.columns.map(column => <th key={column} className="px-3 py-2 font-medium">{column}</th>)}</tr></thead><tbody>{block.rows.map((row, index) => <tr key={index} className="border-b border-[#202129] last:border-0 text-zinc-300">{row.map((cell, cellIndex) => <td key={cellIndex} className="px-3 py-2">{cell}</td>)}</tr>)}</tbody></table></div></div>;
  if (block.type === 'chart') { const Chart = block.kind === 'bar' ? BarChart : LineChart; return <div className={`${shell} p-3`}><div className="mb-2 text-sm text-zinc-300">{block.title}</div><div className="h-56 w-full"><ResponsiveContainer width="100%" height="100%"><Chart data={block.data}><CartesianGrid stroke="#25262d" /><XAxis dataKey={block.xKey} stroke="#71717a" fontSize={11} /><YAxis stroke="#71717a" fontSize={11} /><Tooltip contentStyle={{ background: '#15161b', border: '1px solid #292a32', color: '#f4f4f5' }} />{block.series.map((series, index) => block.kind === 'bar' ? <Bar key={series} dataKey={series} fill={index ? '#71717a' : '#f4f4f5'} radius={[3, 3, 0, 0]} /> : <Line key={series} type="monotone" dataKey={series} stroke={index ? '#a1a1aa' : '#f4f4f5'} strokeWidth={2} dot={false} />)}</Chart></ResponsiveContainer></div></div>; }
  if (block.type === 'file-tree') return <div className={`${shell} p-3`}><div className="mb-2 text-sm text-zinc-300">{block.title ?? 'Files'}</div><div className="space-y-1 font-mono text-xs text-zinc-400">{block.files.map(file => <div key={file.path} className="flex items-center gap-2"><span className="text-zinc-600">{file.type === 'folder' ? <Folder className="h-3.5 w-3.5" /> : <File className="h-3.5 w-3.5" />}</span>{file.path}</div>)}</div></div>;
  return <div className={`${shell} p-3 font-mono text-xs`}><div className="flex items-center gap-2 text-zinc-300"><TerminalIcon className="h-3.5 w-3.5" />{block.title ?? 'Terminal'}<span className={`ml-auto ${block.status === 'error' ? 'text-rose-400' : block.status === 'success' ? 'text-emerald-400' : 'text-zinc-500'}`}>{block.status ?? 'ready'}</span></div>{block.command && <div className="mt-3 text-zinc-300">$ {block.command}</div>}{block.output && <pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap text-zinc-500">{block.output}</pre>}</div>;
}

function FormBlock({ block, onAction, shell }: { block: Extract<NativeBlock, { type: 'form' }>; onAction?: (action: string, payload?: Record<string, string>) => void; shell: string }) {
  const [values, setValues] = useState<Record<string, string>>({});
  return <form className={`${shell} p-4`} onSubmit={event => { event.preventDefault(); onAction?.(block.action ?? 'form_submit', values); }}><div className="text-sm font-medium text-zinc-200">{block.title}</div><div className="mt-3 space-y-2">{block.fields.map(field => <label key={field.name} className="block text-xs text-zinc-400">{field.label}<input required={field.required} type={field.type === 'textarea' ? undefined : field.type ?? 'text'} placeholder={field.placeholder} value={values[field.name] ?? ''} onChange={event => setValues(prev => ({ ...prev, [field.name]: event.target.value }))} className="mt-1 w-full rounded-md border border-[#292a32] bg-[#0b0c0f] px-3 py-2 text-sm text-zinc-200 outline-none focus:border-zinc-500" /> </label>)}</div><button type="submit" className="mt-3 inline-flex items-center gap-2 rounded-md bg-zinc-100 px-3 py-1.5 text-xs font-medium text-zinc-950 hover:bg-white"><Send className="h-3.5 w-3.5" />{block.submitLabel ?? 'Continue'}</button></form>;
}
